Iris classification using ANN

In [1]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
import matplotlib as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.utils import to_categorical


from matplotlib import pyplot as plt

In [2]:
#importing the dataset
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
# store feature matrix in "X"
X = iris.data

# store response vector in "y"
output = iris.target
"""
The output of iris.target provides a intergar categorical data. 
Multi-class classification requires a hot encoded output value.
The iris.target categorical value corresponds to following iris species:
"0": setosa
"1": versicolor
"2": virginica
"""
#Using one hot encoding
y = to_categorical(output)

In [4]:
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Define a two hidden layer ANN architecture

In [6]:
def ANN_model(hiddenLayerOne, hiddenLayerTwo, learnRate, dropout):
    model = Sequential()
    model.add(Dense(hiddenLayerOne, input_shape=(4,), activation='relu', name='fc1'))
    model.add(Dropout(dropout))
    model.add(Dense(hiddenLayerTwo, activation='relu', name='fc2'))
    model.add(Dropout(dropout))
    model.add(Dense(3, activation='softmax', name='output'))
    model.compile(optimizer= Adam(learning_rate=learnRate), loss='categorical_crossentropy', metrics=['accuracy']) #compile the model
    return model

In [7]:
model = ANN_model(5,2,0.001,0)

In [8]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 5)                 25        
_________________________________________________________________
dropout (Dropout)            (None, 5)                 0         
_________________________________________________________________
fc2 (Dense)                  (None, 2)                 12        
_________________________________________________________________
dropout_1 (Dropout)          (None, 2)                 0         
_________________________________________________________________
output (Dense)               (None, 3)                 9         
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
# Train the model
#callback = tensorflow.keras.callbacks.EarlyStopping(monitor='loss', patience=20)
model.fit(X_train, y_train, validation_data = (X_test, y_test), verbose=2, batch_size=40, epochs=100)

Epoch 1/100
3/3 - 0s - loss: 1.0277 - accuracy: 0.6952 - val_loss: 1.0644 - val_accuracy: 0.6000
Epoch 2/100
3/3 - 0s - loss: 1.0052 - accuracy: 0.6952 - val_loss: 1.0442 - val_accuracy: 0.6000
Epoch 3/100
3/3 - 0s - loss: 0.9832 - accuracy: 0.6952 - val_loss: 1.0253 - val_accuracy: 0.6000
Epoch 4/100
3/3 - 0s - loss: 0.9651 - accuracy: 0.6952 - val_loss: 1.0169 - val_accuracy: 0.6000
Epoch 5/100
3/3 - 0s - loss: 0.9582 - accuracy: 0.6857 - val_loss: 1.0168 - val_accuracy: 0.5778
Epoch 6/100
3/3 - 0s - loss: 0.9543 - accuracy: 0.6857 - val_loss: 1.0142 - val_accuracy: 0.5778
Epoch 7/100
3/3 - 0s - loss: 0.9497 - accuracy: 0.6857 - val_loss: 1.0096 - val_accuracy: 0.5778
Epoch 8/100
3/3 - 0s - loss: 0.9437 - accuracy: 0.6857 - val_loss: 1.0035 - val_accuracy: 0.5778
Epoch 9/100
3/3 - 0s - loss: 0.9375 - accuracy: 0.6857 - val_loss: 0.9968 - val_accuracy: 0.6000
Epoch 10/100
3/3 - 0s - loss: 0.9313 - accuracy: 0.6857 - val_loss: 0.9906 - val_accuracy: 0.6000
Epoch 11/100
3/3 - 0s - loss:

In [10]:
results = model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 502us/step - loss: 0.6136 - accuracy: 0.5778


In [11]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.613643
Final test set accuracy: 0.577778


Tuning the Hyperparameters

In [12]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
tensorflow.random.set_seed(42)

# create model
model = KerasClassifier(build_fn=ANN_model, verbose=0)
# define the grid search parameters
hiddenLayerOne = [3, 5, 10, 15, 25]
hiddenLayerTwo = [2, 3, 5,10]
learnRate = [1e-2, 1e-3, 1e-4]
dropout = [0.2, 0.3, 0.4, 0.5]
batchSize = [5, 10, 25, 50]
epochs = [100, 150, 200]

In [13]:
# create a dictionary from the hyperparameter grid
grid = dict(hiddenLayerOne=hiddenLayerOne,hiddenLayerTwo=hiddenLayerTwo,learnRate=learnRate, dropout=dropout,batch_size=batchSize,epochs=epochs) #removed dropout
# initialize a random search with a 3-fold cross-validation and then start the hyperparameter search process
print("[INFO] performing random search...")
Hype_tune = RandomizedSearchCV(estimator=model, n_jobs=-1, cv=3, param_distributions=grid, scoring="accuracy")
#callback = tensorflow.keras.callbacks.EarlyStopping(monitor='loss', patience=30)
Tune_results = Hype_tune.fit(X_train, y_train)
# summarize grid search information
bestScore = Tune_results.best_score_
bestParams = Tune_results.best_params_
print("[INFO] best score is {:.2f} using {}".format(bestScore, bestParams))

[INFO] performing random search...


C:\Users\Vivupadi\Anaconda3\envs\tensorflow_env\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]
  category=UserWarning,


[INFO] best score is nan using {'learnRate': 0.0001, 'hiddenLayerTwo': 10, 'hiddenLayerOne': 10, 'epochs': 200, 'dropout': 0.3, 'batch_size': 5}


In [14]:
# extract the best model, make predictions on our data, and show a classification report
print("[INFO] evaluating the best model...")
bestModel = Tune_results.best_estimator_
accuracy = bestModel.score(X_test, y_test)
print("accuracy: {:.2f}%".format(accuracy * 100))

[INFO] evaluating the best model...
accuracy: 93.33%
